# Generated by Django 5.2.5 on 2025-08-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comptable',
            field=models.ForeignKey(limit_choices_to={'role': 'comptable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_assignes', to=settings.AUTH_USER_MODEL),
        ),
    ]
